# Generated by Django 5.1.2 on 2025-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(choices=[('Ford', 'Ford'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes')], max_length=300)),
                ('carmodel', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
